//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlienTek_Firmware_Upgrade_Tool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlienTek_Firmware_Upgrade_Tool.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App written by.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts of the underlying protocol are based on the original AlienTek Firmware Upgrade Tool.
        /// </summary>
        public static string AboutProtocol {
            get {
                return ResourceManager.GetString("AboutProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlienTek Firmware Upgrade Tool.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit them at.
        /// </summary>
        public static string AboutVisit {
            get {
                return ResourceManager.GetString("AboutVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back.
        /// </summary>
        public static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment entry Bootloader，Reconnecting.......
        /// </summary>
        public static string BootloaderReconnecting {
            get {
                return ResourceManager.GetString("BootloaderReconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string btAbout {
            get {
                return ResourceManager.GetString("btAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Upgrade From Server.
        /// </summary>
        public static string btDownload {
            get {
                return ResourceManager.GetString("btDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Firmware.
        /// </summary>
        public static string btFlashFirmware {
            get {
                return ResourceManager.GetString("btFlashFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string btGetStarted {
            get {
                return ResourceManager.GetString("btGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string btNext {
            get {
                return ResourceManager.GetString("btNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Local Firmware File.
        /// </summary>
        public static string btPickFile {
            get {
                return ResourceManager.GetString("btPickFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string btRefresh {
            get {
                return ResourceManager.GetString("btRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry / See Log.
        /// </summary>
        public static string btRetry {
            get {
                return ResourceManager.GetString("btRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string btStartOver {
            get {
                return ResourceManager.GetString("btStartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Press and hold the button closest to the Screen.
        /// </summary>
        public static string ConnectionInstructionStep1 {
            get {
                return ResourceManager.GetString("ConnectionInstructionStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Connect the soldering iron with a data cable to this Computer.
        /// </summary>
        public static string ConnectionInstructionStep2 {
            get {
                return ResourceManager.GetString("ConnectionInstructionStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Not Open. Did you disconnect the device?.
        /// </summary>
        public static string ConnectionNotOpen {
            get {
                return ResourceManager.GetString("ConnectionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected as.
        /// </summary>
        public static string ConntectedAs {
            get {
                return ResourceManager.GetString("ConntectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data anomalies.
        /// </summary>
        public static string DataAnomalies {
            get {
                return ResourceManager.GetString("DataAnomalies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Devices.
        /// </summary>
        public static string DetectedDevices {
            get {
                return ResourceManager.GetString("DetectedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device is not connected or has been disconnected, please reconnect.
        /// </summary>
        public static string DeviceNotConnected {
            get {
                return ResourceManager.GetString("DeviceNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End instruction exception.
        /// </summary>
        public static string EndInstructionException {
            get {
                return ResourceManager.GetString("EndInstructionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End OK.
        /// </summary>
        public static string EndOK {
            get {
                return ResourceManager.GetString("EndOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in getting device information.
        /// </summary>
        public static string ExceptionGettingDeviceInformation {
            get {
                return ResourceManager.GetString("ExceptionGettingDeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Receiving Device Info.
        /// </summary>
        public static string FailureReceivingDeviceInfo {
            get {
                return ResourceManager.GetString("FailureReceivingDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATK File|*.atk.
        /// </summary>
        public static string FileDialogFilename {
            get {
                return ResourceManager.GetString("FileDialogFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Download Failed.
        /// </summary>
        public static string FirmwareDownloadFailed {
            get {
                return ResourceManager.GetString("FirmwareDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware file not found.
        /// </summary>
        public static string FirmwareFileNotFound {
            get {
                return ResourceManager.GetString("FirmwareFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware information abnormality.
        /// </summary>
        public static string FirmwareInformationAbnormality {
            get {
                return ResourceManager.GetString("FirmwareInformationAbnormality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Information OK.
        /// </summary>
        public static string FirmwareInformationOK {
            get {
                return ResourceManager.GetString("FirmwareInformationOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected firmware is not compatible with this Device.
        /// </summary>
        public static string FirmwareModelMismatch {
            get {
                return ResourceManager.GetString("FirmwareModelMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing Failed.
        /// </summary>
        public static string FlashingFailed {
            get {
                return ResourceManager.GetString("FlashingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Getting Device Info.
        /// </summary>
        public static string GetDeviceInfoError {
            get {
                return ResourceManager.GetString("GetDeviceInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get device information OK.
        /// </summary>
        public static string GetDeviceInformationOK {
            get {
                return ResourceManager.GetString("GetDeviceInformationOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get device status .
        /// </summary>
        public static string GetDeviceStatus {
            get {
                return ResourceManager.GetString("GetDeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Firmware.
        /// </summary>
        public static string LoadingFirmware {
            get {
                return ResourceManager.GetString("LoadingFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MSGTitleError {
            get {
                return ResourceManager.GetString("MSGTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Upgrade Tool for AlienTek T80 and T80D Soldering Irons.
        /// </summary>
        public static string P1Title {
            get {
                return ResourceManager.GetString("P1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting The Device.
        /// </summary>
        public static string P2Title {
            get {
                return ResourceManager.GetString("P2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start abnormal.
        /// </summary>
        public static string StartAbnormal {
            get {
                return ResourceManager.GetString("StartAbnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start OK.
        /// </summary>
        public static string StartOK {
            get {
                return ResourceManager.GetString("StartOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Upgrade Failed!.
        /// </summary>
        public static string UpgradeFailed {
            get {
                return ResourceManager.GetString("UpgradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Upgrade Successful!.
        /// </summary>
        public static string UpgradeSuccessful {
            get {
                return ResourceManager.GetString("UpgradeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via.
        /// </summary>
        public static string via {
            get {
                return ResourceManager.GetString("via", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlienTek Firmware Upgrade.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
